<?php
foreach($_REQUEST as $key => $val){
	if(empty($val))
		unset($_REQUEST[$key]);
}

$requiredFields = array('LeadType', 'Firstname', 'Lastname', 'Phone', 'SeminarGroupId', 'TourCode');
foreach($requiredFields as $req){
	if(!array_key_exists($req, $_REQUEST)){
		echo "Error: Missing " . $req . " Field";
		die;
	}
}

$map = array(
        'LeadType'      => (isset($_REQUEST['LeadType'])) 	? $_REQUEST['LeadType'] 	: '',
        'Firstname'     => (isset($_REQUEST['Firstname'])) 	? $_REQUEST['Firstname'] 	: '',
        'Lastname'      => (isset($_REQUEST['Lastname'])) 	? $_REQUEST['Lastname'] 	: '',
        'Address'       => (isset($_REQUEST['Address'])) 	? $_REQUEST['Address'] 		: '',
        'Address2'      => (isset($_REQUEST['Address2'])) 	? $_REQUEST['Address2'] 	: '',
        'City'          => (isset($_REQUEST['City'])) 		? $_REQUEST['City'] 		: '',
        'State'         => (isset($_REQUEST['State'])) 		? $_REQUEST['State'] 		: '',
        'Zipcode'       => (isset($_REQUEST['Zipcode'])) 	? $_REQUEST['Zipcode'] 		: '',
        'Email'         => (isset($_REQUEST['Email'])) 		? $_REQUEST['Email'] 		: '',
        'Phone'         => (isset($_REQUEST['Phone'])) 		? $_REQUEST['Phone'] 		: '',
        'CellPhone'     => (isset($_REQUEST['CellPhone'])) 	? $_REQUEST['CellPhone'] 	: '',
        'Guest'         => (isset($_REQUEST['Guest'])) 		? $_REQUEST['Guest'] 		: '',
        'Registerdate'  => (isset($_REQUEST['Registerdate'])) 	? date('Y-m-d H:i:s', strtotime($_REQUEST['Registerdate'])) 	: date('Y-m-d H:i:s'),
        'SeminarGroupId' => (isset($_REQUEST['SeminarGroupId'])) ? $_REQUEST['SeminarGroupId'] : '',
        'TourCode'      => (isset($_REQUEST['TourCode'])) 	? $_REQUEST['TourCode'] 	: '',
        'VIPcode'       => (isset($_REQUEST['VIPcode'])) 	? $_REQUEST['VIPcode'] 		: '',
        'ExternalID'    => (isset($_REQUEST['ExternalID'])) 	? $_REQUEST['ExternalID'] 	: ''
);


$db_host = "OR-TSSQL01.response.corp";
$db_user = "dwWEIci16rGByGw8";
$db_pass= "R22tCY2kkK8UguFU";
$database = "DBA";

$dbhandle = mssql_connect($db_host, $db_user, $db_pass) or die("could not connect to sql server on $serverName");
$selected = mssql_select_db($database, $dbhandle) or die("could not connect to database $database");

$sqlC = "";
$sqlV = "";
foreach($map as $k => $v){
	$sqlC .= $k . ",";
	$sqlV .= "'" . $v . "',";
}
$sqlC = substr($sqlC, 0, strlen($sqlC)-1);             //this gets rid of the last comma in the string generated by the forloop
$sqlV = substr($sqlV, 0, strlen($sqlV)-1);

$sql =<<<EOD
	INSERT INTO Registration($sqlC,Leadid,ParentID)
	VALUES($sqlV,'','')
	SELECT @@IDENTITY AS id
EOD;
$query = mssql_query($sql);
$row = mssql_fetch_array($query);
if($row['id'])
	echo "Success: " . $row['id'];
else
	echo "There was an error: Please contact Administrator";

?>
